# -*- coding: utf-8 -*-
#
# filesystem/console/tests/console_test.py
# FileSystemPro
#
# Created by Heitor Bisneto on 12/11/2025.
# Copyright © 2023–2025 hbisneto. All rights reserved.
#
# This file is part of FileSystemPro.
# FileSystemPro is free software: you can redistribute it and/or modify
# it under the terms of the MIT License. See LICENSE for more details.
#

from .. import console

print("="*80)
print("[BRIGHT COLORS]")
print("="*80)
print(console.light_black().bright()('Bright color!'))
print(console.light_blue().bright()('Bright color!'))
print(console.light_cyan().bright()('Bright color!'))
print(console.light_green().bright()('Bright color!'))
print(console.light_magenta().bright()('Bright color!'))
print(console.light_red().bright()('Bright color!'))
print(console.light_white().bright()('Bright color!'))
print(console.light_yellow().bright()('Bright color!'))
print(console.black().bright()('Bright color!'))
print(console.blue().bright()('Bright color!'))
print(console.cyan().bright()('Bright color!'))
print(console.green().bright()('Bright color!'))
print(console.magenta().bright()('Bright color!'))
print(console.red().bright()('Bright color!'))
print(console.yellow().bright()('Bright color!'))
print(console.white().bright()('Bright color!'))
print()

print("="*80)
print("[UNDERLINE COLORS]")
print("="*80)
print(console.light_black().underline()('Underline style!'))
print(console.light_blue().underline()('Underline style!'))
print(console.light_cyan().underline()('Underline style!'))
print(console.light_green().underline()('Underline style!'))
print(console.light_magenta().underline()('Underline style!'))
print(console.light_red().underline()('Underline style!'))
print(console.light_white().underline()('Underline style!'))
print(console.light_yellow().underline()('Underline style!'))
print(console.black().underline()('Underline style!'))
print(console.blue().underline()('Underline style!'))
print(console.cyan().underline()('Underline style!'))
print(console.green().underline()('Underline style!'))
print(console.magenta().underline()('Underline style!'))
print(console.red().underline()('Underline style!'))
print(console.yellow().underline()('Underline style!'))
print(console.white().underline()('Underline style!'))
print()

print("="*80)
print("[STRIKETHROUGH COLORS]")
print("="*80)
print(console.light_black().strikethrough()('Strikethrough style!'))
print(console.light_blue().strikethrough()('Strikethrough style!'))
print(console.light_cyan().strikethrough()('Strikethrough style!'))
print(console.light_green().strikethrough()('Strikethrough style!'))
print(console.light_magenta().strikethrough()('Strikethrough style!'))
print(console.light_red().strikethrough()('Strikethrough style!'))
print(console.light_white().strikethrough()('Strikethrough style!'))
print(console.light_yellow().strikethrough()('Strikethrough style!'))
print(console.black().strikethrough()('Strikethrough style!'))
print(console.blue().strikethrough()('Strikethrough style!'))
print(console.cyan().strikethrough()('Strikethrough style!'))
print(console.green().strikethrough()('Strikethrough style!'))
print(console.magenta().strikethrough()('Strikethrough style!'))
print(console.red().strikethrough()('Strikethrough style!'))
print(console.yellow().strikethrough()('Strikethrough style!'))
print(console.white().strikethrough()('Strikethrough style!'))
print()

print("="*80)
print("[BACKGROUND COLORS]")
print("="*80)
print(console.light_black().white_bg()('Background color style!'))
print(console.light_blue().yellow_bg()('Background color style!'))
print(console.light_cyan().red_bg()('Background color style!'))
print(console.light_green().magenta_bg()('Background color style!'))
print(console.light_magenta().green_bg()('Background color style!'))
print(console.light_red().cyan_bg()('Background color style!'))
print(console.light_white().blue_bg()('Background color style!'))
print(console.light_yellow().black_bg()('Background color style!'))
print(console.black().light_yellow_bg()('Background color style!'))
print(console.blue().light_white_bg()('Background color style!'))
print(console.cyan().light_red_bg()('Background color style!'))
print(console.green().light_magenta_bg()('Background color style!'))
print(console.magenta().light_green_bg()('Background color style!'))
print(console.red().light_cyan_bg()('Background color style!'))
print(console.yellow().light_blue_bg()('Background color style!'))
print(console.white().light_black_bg()('Background color style!'))
print()
